language: node_js
sudo: true
node_js:
  - '4.4.2'
services: mongodb
cache:
  directories:
    - node_modules
before_install:
  - npm install
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm run start
  - npm test
after_script:
  - npm run coverage