language: node_js
sudo: true
node_js:
  - '4.4.2'
services: mongodb
cache:
  directories:
    - node_modules
before_install:
    - npm install
script:
  - npm run start
  - npm test
after_script:
  - npm run coverage